set(MANDELBROT_WRAPPER_LIB "lib_mandelbrot_wrapper")

file(GLOB C_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c)
file(GLOB C_HEADERS CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/include/mandelbrot/*.h)

add_library(${MANDELBROT_WRAPPER_LIB} STATIC ${C_SOURCES} ${C_HEADERS})

target_include_directories(${MANDELBROT_WRAPPER_LIB} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(${MANDELBROT_WRAPPER_LIB} PUBLIC lib_common)
